Comment atlassian dependency to prevent conflicts
The generated error is described below:

Collecting atlassian-python-api==0.13.2
  Using cached atlassian_python_api-0.13.2-cp35-none-any.whl
ERROR: Cannot install -r tubular/requirements.txt (line 1) and requests<3.0 and >=2.9.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests<3.0 and >=2.9.1
    atlassian-python-api 0.13.2 depends on requests==2.7.0